  ugonnawin-slash-commands:
    image: oze4/ugonnawin-slash-commands:latest
    container_name: ugonnawin-slash-commands
    depends_on:
      - "traefik"
    restart: "always"
    labels:
      - "traefik.port=redacted"
      - "traefik.frontend.rule=Host:ugonnawin.redacted.com"
    environment:
      - PORT=redacted                                                                 
      - APP_ID=redacted
      - CLIENT_ID=redacted                                                                                 
      - CLIENT_SECRET=redacted
      - SIGNING_SECRET=redacted
      - VERIFICATION_TOKEN=redacted