FROM node:latest

ARG APP_ID
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG SIGNING_SECRET
ARG VERIFICATION_TOKEN
ARG PORT

ENV APP_ID=${APP_ID}
ENV CLIENT_ID=${CLIENT_ID}
ENV CLIENT_SECRET=${CLIENT_SECRET}}
ENV SIGNING_SECRET=${SIGNING_SECRET}}
ENV VERIFICATION_TOKEN=${VERIFICATION_TOKEN}}
ENV PORT=${PORT}}

WORKDIR /app
COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

EXPOSE ${PORT}
CMD ["npm", "start"]