apiVersion: v1
kind: Service
metadata:
  name: ugonnawin-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ugonnawin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugonnawin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ugonnawin
  template:
    metadata:
      labels:
        app: ugonnawin
    spec:
      containers:
      - name: ugonnawin
        image: oze4/ugonnawin-slash-commands:latest
        env:
        - name: PORT
          value: ${PORT}
        - name: APP_ID
          value: ${APP_ID}
        - name : CLIENT_ID
          value: ${CLIENT_ID}
        - name: CLIENT_SECRET
          value: ${CLIENT_SECRET}
        - name: SIGNING_SECRET
          value: ${SIGNING_SECRET}
        - name: VERIFICATION_TOKEN
          value: ${VERIFICATION_TOKEN}
        - name: INCOMING_WEB_HOOK_URL
          value: ${INCOMING_WEB_HOOK_URL}
        - name: OAUTH_ACCESS_TOKEN
          value: ${OAUTH_ACCESS_TOKEN}
        - name: BOT_OAUTH_ACCESS_TOKEN
          value: ${BOT_OAUTH_ACCESS_TOKEN}
        - name: OPENWEATHERMAP_API_KEY
          value: ${OPENWEATHERMAP_API_KEY}
        - name: OPENWEATHERMAP_BASE_URL
          value: ${OPENWEATHERMAP_BASE_URL}
        - name: MONGO_CONNECTION_STRING
          value: ${MONGO_CONNECTION_STRING}
        - name: MONGO_DATABASE
          value: ${MONGO_DATABASE}
        - name: MONGO_COLLECTION
          value: ${MONGO_COLLECTION}
        ports:
        - containerPort: 80  
---
